export const REGISTER_SUCCESS= 'REGISTER_SUCCESS';
export const LOGIN_SUCCESS= 'LOGIN_SUCCESS';
export const REGISTER_FAIL= 'REGISTER_FAIL';
export const LOGIN_FAIL= 'LOGIN_FAIL';
export const USER_LOADED= 'USER_LOADED';
export const AUTH_ERROR= 'AUTH_ERROR';
export const LOGOUT= 'LOGOUT';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';

export const LOAD_PROJECTS = 'LOAD_PROJECTS';
export const REMOVE_PROJECT = 'REMOVE_PROJECT';
export const REMOVE_PROJECT_FAILURE = 'REMOVE_PROJECT_FAILURE';


export const ADD_ISSUE = 'ADD_ISSUE';
export const ADD_ISSUE_FAILURE = 'ADD_ISSUE_FAILURE';
export const UPDATE_ISSUE = 'UPDATE_ISSUE'
export const UPDATE_ISSUE_FAILURE = 'UPDATE_ISSUE_FAILURE'
export const REMOVE_ISSUE = 'REMOVE_ISSUE';
export const REMOVE_ISSUE_FAILURE = 'REMOVE_ISSUE_FAILURE'

export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const UPDATE_PROFILE_FAILURE = 'UPDATE_PROFILE_FAILURE';

export const CHANGE_SELECTED = 'CHANGE_SELECTED';
export const CHANGE_SELECTED_FAILURE = 'CHANGE_SELECTED_FAILURE';
export const ADD_USER_PROJECT_SUCCESS = 'ADD_USER_PROJECT_SUCCESS';
export const ADD_USER_PROJECT_FAILURE = 'ADD_USER_PROJECT_FAILURE';
export const CREATE_PROJECT_SUCCESS = 'CREATE_PROJECT_SUCCESS';
export const CREATE_PROJECT_FAILURE = 'CREATE_PROJECT_FAILURE';
export const POST_ISSUE_MESSAGE_SUCCESS = 'POST_ISSUE_MESSAGE_SUCCESS';
export const POST_ISSUE_MESSAGE_FAILURE = 'POST_ISSUE_MESSAGE_FAILURE';

export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const LOAD_TODOS_SUCCESS = 'LOAD_TODOS_SUCCESS';
export const LOAD_TODOS_FAILURE = 'LOAD_TODOS_FAILURE';
export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS';
export const ADD_TODO_FAILURE = 'ADD_TODO_FAILURE';
export const REMOVE_TODO_SUCCESS = 'REMOVE_TODO_SUCCESS';
export const REMOVE_TODO_FAILURE = 'REMOVE_TODO_FAILURE';
export const UPDATE_TODO_SUCCESS = 'UPDATE_TODO_SUCCESS';
export const UPDATE_TODO_FAILURE = 'UPDATE_TODO_FAILURE';
export const FILTER_TODOS = 'FILTER_TODOS';
export const FILTER_TODOS_FAILURE = 'FILTER_TODOS_FAILURE';

export const ADD_NOTIFICATION_SUCCESS = 'ADD_NOTIFICATION_SUCCESS';
export const ADD_NOTIFICATION_FAILURE = 'ADD_NOTIFICATION_FAILURE';
export const DELETE_NOTIFICATION_SUCCESS = 'DELETE_NOTIFICATION_SUCCESS';
export const DELETE_NOTIFICATION_FAILURE = 'DELETE_NOTIFICATION_FAILURE';
export const MARK_AS_READ_FAILURE = 'MARK_AS_READ_FAILURE';
export const MARK_AS_READ_SUCCESS= 'MARK_AS_READ_SUCCESS';


